cat("Sourcing testfunctions (to load test data)\n")
source("testfunctions.R")
t <- Sys.time()
cat("Loading testdata ...\n")
xxx <- get_testdata(1000000, 1000, TRUE)
t <- as.numeric(Sys.time() - t, units = "mins")
cat("\n\nJust reading the test data took ", round(t, 2), " minutes\n")
